export default nachos = [
    {name:"Regular Nachos"},
    {name:"Crazy Nachos"},
    {name:"Spicy Nachos"},
    {name:"Veggie Nachos"},
    {name:"Meaty Nachos"},
    {name:"Cheesy Nachos"},
    {name:"Pizza Cheese Nachos"},
    {name:"Beans Nachos"},
    {name:"Rice Nachos"},
    {name:"Buffalo Nachos"},
    {name:"Cowboy Nachos"},
    {name:"Mole Nachos"},
    {name:"Barbecue Nachos"},
    {name:"Chicken Nachos"},
    {name:"Loaded Barbecue Chicken Nachos"},
    {name:"Baked Nachos"},
    {name:"Southern Nachos"},
    {name:"Fresh Crab Nachos"},
    {name:"Fajita Nachos"},
    {name:"Spicy Sausage Ragu Nachos"},
    {name:"Roasted Sweet Potato Nachos"},
    {name:"Leftover Thanksgiving Nachos"},
    {name:"Bacon BBQ Nachos"},
    {name:"Citrus Shrimp Nachos"},
    {name:"Jerk Pork Nachos"},
    {name:"Breakfast Nachos"},
    {name:"Greek Pita Nachos"},
    {name:"Grilled Loaded Nachos"},
    {name:"Fall Nachos"},
    {name:"Homemade Nachos"},
    {name:"Plantain Chip Nachos"},
    {name:"Thai Beef Nachos"},
    {name:"BBQ Pulled Pork Nachos"},
    {name:"Dessert Nachos"},
    {name:"Cubano Nachos"},
    {name:"Guy-Talian Nachos"},
    {name:"Cheeseburger Nachos"},
    {name:"5-Star Nachos"},
    {name:"Pizza Nachos"},
    {name:"Taco Nachos"},
]