export default nachos = [
    {name:"Regular Nachos"}, {category:"Normal"},
    {name:"Crazy Nachos"}, {category:"Cheese and Vegetable"},
    {name:"Spicy Nachos"}, {category:"Spice"},
    {name:"Veggie Nachos"}, {category:"Vegetable"},
    {name:"Meaty Nachos"}, {category:"Meat"},
    {name:"Cheesy Nachos"}, {category:"Cheese"},
    {name:"Mozzarella Cheese Nachos"}, {category:"Cheese"},
    {name:"Beans Nachos"}, {category:"Vegetable"},
    {name:"Rice Nachos"}, {category:"Grains"},
    {name:"Buffalo Nachos"}, {category:"Meat"},
    {name:"Cowboy Nachos"}, {category:"Vegetable"},
    {name:"Mole Nachos"}, {category:"Spice"},
    {name:"Barbecue Nachos"}, {category:"Spice"},
    {name:"Chicken Nachos"}, {category:"Meat"},
    {name:"Loaded Barbecue Chicken Nachos"}, {category:"Spice and Meat"},
    {name:"Baked Nachos"}, {category:"Cheese and Meat"},
    {name:"Southern Nachos"}, {category:"Meat"},
    {name:"Fresh Crab Nachos"}, {category:"Vegetable and Meat"},
    {name:"Fajita Nachos"}, {category:"Meat"},
    {name:"Spicy Sausage Ragu Nachos"}, {category:"Vegetable and Meat"},
    {name:"Roasted Sweet Potato Nachos"}, {category:"Meat"},
    {name:"Leftover Thanksgiving Nachos"}, {category:"Cheese and Vegetable"},
    {name:"Bacon BBQ Nachos"}, {category:"Vegetable, Spice, and Meat"},
    {name:"Citrus Shrimp Nachos"}, {category:"Meat"},
    {name:"Jerk Pork Nachos"}, {category:"Vegetable and Meat"},
    {name:"Breakfast Nachos"}, {category:"Meat"},
    {name:"Greek Pita Nachos"}, {category:"Vegetable"},
    {name:"Grilled Loaded Nachos"}, {category:"Spice"},
    {name:"Fall Nachos"}, {category:"Vegetable and Meat"},
    {name:"Homemade Nachos"}, {category:"Cheese and Meat"},
    {name:"Plantain Chip Nachos"}, {category:"Spice and Meat"},
    {name:"Thai Beef Nachos"}, {category:"Meat"},
    {name:"BBQ Pulled Pork Nachos"}, {category:"Vegetable, Spice, and Meat"},
    {name:"Dessert Nachos"}, {category:"Fruit"},
    {name:"Cubano Nachos"}, {category:"Cheese and Meat"},
    {name:"Guy-Talian Nachos"}, {category:"Cheese, Vegetable, and Meat"},
    {name:"Cheeseburger Nachos"}, {category:"Cheese and Meat"},
    {name:"5-Star Nachos"}, {category:"Cheese and Vegetable"},
    {name:"Pizza Nachos"}, {category:"Cheese and Spice"},
    {name:"Taco Nachos"}, {category:"Cheese and Meat"},
]